### ISSUE TITLE
Detecting Available Can Network

### ISSUE THREAD

**Issue by CaptChrisD** [tonyrog/can#3]
Is it possible to detect if there is a valid can bus available? In other words is there a way to detect if the transceiver is getting bus power?

Thanks in advance

**Comment by tonyrog** [comment]
I have not checked, so I do not know. You can use netlink (Feuerlabs) to detect can links going up and down (not fully supported) and you can use ifconfig to see if your hardware support this. If you find out if this is possibe I am interested to know :-)

**Comment by CaptChrisD** [comment]
No longer working on this project so closing comment
