### ISSUE TITLE
undefined function can_counter.get_all/0

### ISSUE THREAD

**Issue by xadhoom** [tonyrog/can#4]
when calling can_router.i/0 , having only one vcan registered into the can router, 
the process crash because can_sock calls can_counter.get_all which does not exists.

here's the crash dump (launched from elixir, so format may be a little different)

iex(4)> :can_router.i
Interfaces
** (exit) exited in: :gen_server.call(#PID<0.155.0>, :statistics)
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) undefined function: :can_counter.get_all/0
            (can) :can_counter.get_all()
            (can) src/can_sock.erl:170: :can_sock.handle_call/3
            (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

the interface is correctly registered and receives can message.
Using latest git as now and otp 18.1

**Comment by tonyrog** [comment]
Thanks! Fixed it. Did a big update recently and missed this one.
