### ISSUE TITLE
Undefined parse transform ‘lager_transform’ with elixir 1.4.0

### ISSUE THREAD

**Issue by xadhoom** [tonyrog/can#6]
Hi,

I'm using can under an elixir project, which works flawlessly.

Now I'm in the process to upgrade to elixir 1.4.0, and I have the error:

> Undefined parse transform ‘lager_transform’

when building. I've detailed the issue here:

https://elixirforum.com/t/undefined-parse-transform-lager-transform-with-elixir-1-4-0

Now I'm not an erlang expert so this maybe not a real bug or just some integration issue,
the only thing that changed is the elixir version, which may have uncovered some packaging 
incosistency?

**Comment by xadhoom** [comment]
seems something related to elixir, as discussed here

https://github.com/elixir-lang/elixir/issues/5640

**Comment by tonyrog** [comment]
Sorry, I am not a elixir user so it is nearly impossible for me to do anything here. But please post more info here if the matter is resolved. Thanks.

**Comment by xadhoom** [comment]
ok,

at the end was an issue in elixir, that has been fixed in a recent commit:
https://github.com/elixir-lang/elixir/pull/5687

thanks!
